export const styles = {
  adviceContainer: {
    width: '100%',
    padding: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    background: '#FFFFFF',
    color: 'black',
    fontSize: '1.5em',
    boxSizing: 'border-box',
    fontFamily: 'MontRegular',
  },
  warning: {
    width: '60px',
    minWidth: '60px',
    height: '60px',
    borderRadius: '50%',
    border: '7px solid red',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'black',
    marginLeft: '10px',
    fontFamily: 'MontRegular',
  },
}
