export const styles = {
  adviceContainer: {
    width: '100%',
    padding: '2vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    background: '#FFFFFF',
    color: 'black',
    fontSize: '2vw',
    boxSizing: 'border-box',
    fontFamily: 'MontItalic',
  },
  warning: {
    width: '4vw',
    minWidth: '4vw',
    height: '4vw',
    borderRadius: '50%',
    border: '7px solid red',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'black',
    marginLeft: '10px',
    fontFamily: 'MontRegular',
  },
}
