/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 glo_device.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glo_device.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Obj_152_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_157_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_153_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_154_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_155_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_156_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_158_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_151_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_163_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_160_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_166_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_161_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_168_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_169_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_177_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_178_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_164_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_176_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_109_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_146_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_145_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_150_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_147_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_144_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_148_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_128_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_143_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_170_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_179_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_165_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_180_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_186_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_173_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_181_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_182_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_171_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_185_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_183_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_184_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_175_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_187_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_172_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_188_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_189_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_174_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_190_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_191_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_192_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_194_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_193_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_202_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_195_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_196_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_197_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_198_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_199_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_200_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_201_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_111_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_149_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_107_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_117_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_113_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_102_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_115_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_112_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_114_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_116_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_104_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_118_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_103_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_105_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_108_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_119_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_120_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_121_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_106_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_122_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_123_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_124_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_125_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_110_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_127_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_138_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_132_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_141_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_126_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_133_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_131_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_139_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_130_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_134_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_142_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_137_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_135_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_136_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_140_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_129_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_162_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_167_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Obj_159_node.geometry} material={materials.wire_140088225} />
      <mesh geometry={nodes.Object001_node.geometry} material={materials.wire_140088225} />
    </group>
  )
}

useGLTF.preload('/glo_device.gltf')
