/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 marpla-watch.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props:any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/marpla-watch.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Wristwatch_TISSOT_1853__PR100" position={[0, 0, -0.046]} rotation={[Math.PI / 2, 0, 0]}
        >
          <group name="adjustment_knob" position={[0.016, 0.052, 0]}>
            <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.013']} />
            <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Material.001']} />
          </group>
          <group name="casing" position={[0, 0.056, 0]}>
            <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['Material.013']} />
            <mesh name="Circle006_1" geometry={nodes.Circle006_1.geometry} material={materials['Material.016']} />
          </group>
          <group name="casing001" position={[0, 0.056, 0]}>
            <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.013']} />
            <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials['Material.017']} />
            <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials['Material.018']} />
          </group>
          <group name="clock_face" position={[0, 0.056, 0]}>
            <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.fur} />
            <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials['Material.013']} />
            <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={materials['Material.015']} />
          </group>
          <mesh name="Glas" geometry={nodes.Glas.geometry} material={materials.Glas} position={[0, 0.055, 0]} />
          <group name="hour_hand" position={[0, 0.056, 0]} rotation={[0, 0.512, 0]}>
            <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Material.013']} />
            <mesh name="Circle004_1" geometry={nodes.Circle004_1.geometry} material={materials['Material.014']} />
          </group>
          <group name="minute_hand" position={[0, 0.056, 0]} rotation={[0, 0.358, 0]}>
            <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.013']} />
            <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials['Material.014']} />
          </group>
          <mesh name="second_hand" geometry={nodes.second_hand.geometry} material={materials['Material.013']} position={[0, 0.056, 0]} />
        </group>
        <group name="Armature" position={[-0.001, -0.009, 0.006]} rotation={[-3.097, -0.182, -0.025]} scale={0.008}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="bracelet001" geometry={nodes.bracelet001.geometry} material={materials['Material.013']} skeleton={nodes.bracelet001.skeleton} />
        </group>
        <group name="Armature002" position={[-0.001, 0.005, 0.005]} rotation={[0.049, 0, 0]} scale={0.012}>
          <primitive object={nodes.Bone_1} />
          <group name="bracelet_clasp001">
            <skinnedMesh name="BezierCircle003" geometry={nodes.BezierCircle003.geometry} material={materials['Material.013']} skeleton={nodes.BezierCircle003.skeleton} />
            <skinnedMesh name="BezierCircle003_1" geometry={nodes.BezierCircle003_1.geometry} material={materials['Material.002']} skeleton={nodes.BezierCircle003_1.skeleton} />
          </group>
          <skinnedMesh name="bracelet_clasp002" geometry={nodes.bracelet_clasp002.geometry} material={materials['Material.013']} skeleton={nodes.bracelet_clasp002.skeleton} />
          <skinnedMesh name="bracelet_clasp003" geometry={nodes.bracelet_clasp003.geometry} material={materials['Material.013']} skeleton={nodes.bracelet_clasp003.skeleton} />
          <skinnedMesh name="bracelet_clasp004" geometry={nodes.bracelet_clasp004.geometry} material={materials['Material.013']} skeleton={nodes.bracelet_clasp004.skeleton} />
          <skinnedMesh name="bracelet002" geometry={nodes.bracelet002.geometry} material={materials['Material.001']} skeleton={nodes.bracelet002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/marpla-watch.gltf')
